<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>13_async&await.html</title>
</head>
<body>
  <script type="text/javascript">
    /**
      async与await
      async函数
        1. 函数的返回值为promise对象
        2. promise对象的结果由async函数执行的返回值决定
      await表达式
        await右侧的表达式一般为promise对象，但也可以是其它的值
        如果表达式是promise对象，await返回的是promise成功的值
        如果表达式时其他值，直接将此值作为await的返回值
      注意：
        await必须写在async函数中，但async函数中可以没有await
        如果await的promise失败了，就会抛出异常，需要通过try...catch来捕获处理
    */

    // async函数的返回值是一个promise对象
    // async函数返回的promise的结果由函数执行的结果决定
    // async function fn() {
    //   // return 1
    //   // throw 2
    //   return new Promise((resolve, reject) => {
    //     setTimeout(() => {
    //       resolve(4)
    //     }, 1000)
    //   })
    // }

    // const result = fn()
    // result.then(
    //   value => {
    //     console.log('onResolved', value)
    //   },
    //   reason => {
    //     console.log('onRejected', reason)
    //   }
    // )

    function foo () {
      return Promise.resolve(2)
    }
    async function bar () {
      // const value = await foo() // await右侧表达式为promise，得到的结果就是promise成功的value
      // const value = await 'async & await' // await右侧表达式不是promise，得到的是这个表达式本身
      // console.log('value', value)
      try {
        const value = await Promise.reject('something wrong')
      } catch (error) {
        console.log(error)
      }
    }
    bar()
  </script>
</body>
</html>